name: KCSSafety
options:
  bundleIdPrefix: com.ugakky
  deploymentTarget:
    iOS: "16.0"
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 13.9.0
  UserMessagingPlatform:
    url: https://github.com/googleads/swift-package-manager-google-user-messaging-platform.git
    from: 3.1.0
targets:
  KCSSafety:
    type: application
    platform: iOS
    sources:
      - KCSSafety
    info:
      path: KCSSafety/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ugakky.kcssafety
        PRODUCT_NAME: KCS Safety
        SWIFT_VERSION: 6.0
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: GoogleMobileAds
        product: GoogleMobileAds
      - package: UserMessagingPlatform
        product: GoogleUserMessagingPlatform
